version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
